grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
model_selection:
  module_0:
    class: CatBoostClassifier
    module: catboost
    params:
      iterations: 10
      learning_rate: 0.1
      depth: 2
    search_param_grid:
      iterations:
      - 10
      - 15
      - 20
      learning_rate:
      - 0.1
      - 0.05
      depth:
      - 2
      - 4
      - 6
   
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      max_depth: 10
      max_features: sqrt
      n_estimators: 3
    search_param_grid:
      max_depth:
      - 10
      - 15
      - 20
      max_features:
      - sqrt
      - log2
      n_estimators:
      - 3
      - 5
      - 9